import { FontOption } from './post-state.interface';

export const DEFAULT_FONTS: FontOption[] = [
  { name: 'Playfair Display', value: "'Playfair Display', serif" },
  { name: 'Cormorant Garamond', value: "'Cormorant Garamond', serif" },
  { name: 'Bodoni Moda', value: "'Bodoni Moda', serif" },
  { name: 'Bebas Neue', value: "'Bebas Neue', sans-serif" },
  { name: 'Space Grotesk', value: "'Space Grotesk', sans-serif" },
  { name: 'Oswald', value: "'Oswald', sans-serif" },
  { name: 'Anton', value: "'Anton', sans-serif" },
  { name: 'Archivo Black', value: "'Archivo Black', sans-serif" },
  { name: 'Abril Fatface', value: "'Abril Fatface', serif" },
  { name: 'Righteous', value: "'Righteous', sans-serif" },
  { name: 'Teko', value: "'Teko', sans-serif" },
  { name: 'Fjalla One', value: "'Fjalla One', sans-serif" },
  { name: 'Montserrat', value: "'Montserrat', sans-serif" },
  { name: 'Raleway', value: "'Raleway', sans-serif" },
  { name: 'Outfit', value: "'Outfit', sans-serif" },
  { name: 'Work Sans', value: "'Work Sans', sans-serif" },
  { name: 'Josefin Sans', value: "'Josefin Sans', sans-serif" },
  { name: 'Libre Franklin', value: "'Libre Franklin', sans-serif" },
  { name: 'Poppins', value: "'Poppins', sans-serif" },
  { name: 'Questrial', value: "'Questrial', sans-serif" },
  { name: 'Karla', value: "'Karla', sans-serif" },
  { name: 'Barlow', value: "'Barlow', sans-serif" },
  { name: 'DM Sans', value: "'DM Sans', sans-serif" },
  { name: 'Rubik', value: "'Rubik', sans-serif" },
  { name: 'Inter', value: "'Inter', sans-serif" },
  { name: 'Lato', value: "'Lato', sans-serif" },
  { name: 'Roboto', value: "'Roboto', sans-serif" },
  { name: 'Source Sans Pro', value: "'Source Sans Pro', sans-serif" },
  { name: 'Nunito Sans', value: "'Nunito Sans', sans-serif" },
];
